# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbus',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 21, 13, 27, 25, 130229), verbose_name='时间'),
        ),
    ]
