# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20170921_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbusschedules',
            name='date_schedule',
            field=models.CharField(max_length=10, verbose_name='时刻'),
        ),
    ]
