# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20170921_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
