# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_auto_20170921_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbus',
            name='num_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='总座位数'),
        ),
    ]
