# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserve', '0008_auto_20170921_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBusReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserve', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发起预约时间')),
            ],
            options={
                'verbose_name': '校车预约',
                'verbose_name_plural': '校车预约',
            },
        ),
        migrations.AlterModelOptions(
            name='schoolbus',
            options={'ordering': ['-date'], 'verbose_name': '校车班次', 'verbose_name_plural': '校车班次'},
        ),
        migrations.AddField(
            model_name='schoolbusreserve',
            name='schoolbus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.SchoolBus', verbose_name='校车班次'),
        ),
        migrations.AddField(
            model_name='schoolbusreserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
