# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_auto_20170922_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
