# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20170922_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbusreserve',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
