# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0017_specialcartravel_date_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialcartravel',
            options={'ordering': ['-date_travel'], 'verbose_name': '专车出行申请', 'verbose_name_plural': '专车出行申请'},
        ),
        migrations.AddField(
            model_name='specialcartravel',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='是否接受'),
        ),
    ]
