# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_auto_20170926_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chartered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='包车联系方式')),
            ],
            options={
                'verbose_name': '包车',
                'verbose_name_plural': '包车',
            },
        ),
    ]
