# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_auto_20170928_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcartimeschedule',
            name='endtime',
            field=models.DateTimeField(blank=True, verbose_name='结束时间'),
        ),
    ]
