# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170919_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='车牌号')),
                ('type', models.IntegerField(choices=[(1, '小车司机'), (2, '校车司机'), (3, '管理者')], verbose_name='司机类型')),
                ('status', models.IntegerField(choices=[(0, '非空闲'), (1, '空闲')], default=0, verbose_name='状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
            ],
            options={
                'verbose_name': '司机',
                'verbose_name_plural': '司机',
            },
        ),
    ]
