# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ucenterreservewrapper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='type',
            field=models.IntegerField(choices=[(1, '专车司机'), (2, '校车司机'), (3, '管理者')], verbose_name='司机类型'),
        ),
    ]
