# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170925_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
    ]
